### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith.io#187]
Would be great if we could allow accessing metalsmith.io over HTTPS. 

This can be done with a GitHub pages site by using Cloudflare. Here's a blog post I found with step-by-step instructions: https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

**Comment by Ajedi32** [comment]
FWIW, we can now do this using a regular GitHub pages site (no Cloudflare needed): https://github.com/metalsmith/metalsmith.io/issues/187

**Comment by axe312ger** [comment]
It should be actually done soon since Chrome will consider pages without HTTPS as harmful soonish

**Comment by SmashManiac** [comment]
Seeing the message "Not Secure" in Chrome because of this issue.

This should be fixed ASAP. This combined with the lack of new releases for 2 years makes it look like the project is dead.

**Comment by axe312ger** [comment]
Jep very true :/

**Comment by ismay** [comment]
Don't want to complicate things, but if we're changing things anyway, maybe we should consider netlify. Live branch preview in PRs is quite nice. We'd need access to metalsmith.io's dns records though.

**Comment by axe312ger** [comment]
Who is owning the domain? Whois does not give any help here.

**Comment by ismay** [comment]
I assume Segment?

**Comment by f2prateek** [comment]
I think we could close this out now?

**Comment by ismay** [comment]
Yeah you’re right. Fixed with the move to netlify.
