### ISSUE TITLE
site is out of date

### ISSUE THREAD

**Issue by ahmadnassri** [metalsmith/metalsmith.io#194]
seems like a numver of pull requests were merged, months ago even ... yet website is still pointing to old content.

**Comment by woodyrew** [comment]
Hi @ahmadnassri thanks. I've merged a critical PR that has allowed us to move forwards with the site. 
The updates have come through on the site now.

**Comment by ahmadnassri** [comment]
excellent, thank you.

**Comment by Ajedi32** [comment]
Yeah, the deploy process is now fully automated so this problem is fixed for good. #149
