### ISSUE TITLE
Adding a detailed walkthrough as a subpage

### ISSUE THREAD

**Issue by lukehler** [metalsmith/metalsmith.io#238]
As mentioned by @Ajedi32 in https://github.com/segmentio/metalsmith/issues/219#issuecomment-287189760, I've got a pull request ready to go with a new, detailed, step-by-step walkthrough (based loosely upon [a wiki page I added to the main repo](https://github.com/segmentio/metalsmith/wiki/The-basics-of-Metalsmith)) as a second page.

Before doing so, I just wanted to provide some advance notice about the updates I'd made. Namely there were a few adjustments to the template and frontmatter to accommodate a second page:

- Updated _index.html_ to use the `title` and `description` in `header.Header` instead of hard-coding the content.
- Updated _src/index.md_ to add the `em` element around "pluggable" to the `description` value in the frontmatter.
- Added swig `striptags` filters to the `meta` values using the description in _index.html_ to strip out the `<em>`.

The end result is that the `head` and `header.Header` both end up with the exact same markup on _build/index.html_ as seen on the current site. I only bring it up because it's not immediately clear if putting markup directly into the frontmatter is verboten (or even just a bad example).

And then there's the actual content changes themselves:

- Added links to the new walkthrough page to the "Welcome" and "Installation" sections on _src/index.md_.
- Note that this does not update the "Further information" section yet, but that seems like the next section to address.
- Added an entirely new page as _src/step-by-step/index.md_.

So I'm happy to submit the pull request, but I wanted to introduce the intent first. I'm not really looking to have this deployed as-is, but I'm happy to share it as a starting point to discuss how to proceed. In addition to the layout considerations, I would really like to hear if there's a particular tone, target audience, or style that the team would prefer.

**Comment by Ajedi32** [comment]
Seems like a reasonable approach at first glance, but it's kinda hard to understand exactly what you're talking about without seeing the diff.

If you've already made all the changes you're describing here, just go ahead and send the PR. Discussion/review of changes made to code is exactly what PRs are for. :wink:

**Comment by webketje** [comment]
Merged the updated PR after review. I think the walkthrough could be made easier to read (removing redundant wording, shortening sentences, perhaps runnin it through something like grammar.ly) but it fulfills its purpose for now. Closing
