### ISSUE TITLE
Massive .psd file in repo

### ISSUE THREAD

**Issue by ghost** [metalsmith/metalsmith.io#240]
There is a *massive* 19mb photoshop file in this repo. Now it's not my repo, but I would certainly take that out.

**Comment by Ajedi32** [comment]
Yeah, I'm not really sure what's up with that. Doesn't look like it's used for anything, I wonder if @ianstormtaylor added it by accident...

In any case, I don't think we need to be rewriting the entire history of the repo just to get rid of that. 19mb is pretty big compared to text, but still not nearly big enough to cause any significant problems just by being in the repo.

**Comment by ismay** [comment]
@Ajedi32 I think it's the file with the originals for the dividers. Probably added it just to have the originals available if we (or he) needed them.
