### ISSUE TITLE
Deploy Failing - API Key Changed

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith.io#251]
The automatic deploy via Travis [is currently failing](https://travis-ci.org/metalsmith/metalsmith.io/jobs/271286964) with the following error message:

```
API request failed.
Message: Invalid credentials provided.
Reference: 
failed to deploy
```

Sounds like the API key specified in `.travis.yml` is no longer valid. As I don't have direct access to the site's settings on Heroku and I don't work at Segment, I have no way to fix this myself. Could someone who _does_ work at Segment please fix this?

CC: @fouad, @lambtron, @dominicbarnes

**Comment by fouad** [comment]
Hey @Ajedi32 I'm not sure what broke it but I just created a new PR updating the secret and will see if that fixes it https://github.com/metalsmith/metalsmith.io/pull/252

**Comment by Ajedi32** [comment]
Yep, that seems to have worked. 👍
