### ISSUE TITLE
Metalsmith Org addition

### ISSUE THREAD

**Issue by woodyrew** [metalsmith/metalsmith.io#271]
Hi @fouad / @lambtron 

Could you add @ismay to the [Metalsmith Org](https://github.com/metalsmith) or make me an owner so I can add them please?

Thanks,
Woody

**Comment by fouad** [comment]
@woodyrew sorry for delay, just saw this issue -- added you as an owner!

**Comment by woodyrew** [comment]
Thank you :)

**Comment by woodyrew** [comment]
@fouad I'm still listed as a member: https://github.com/orgs/metalsmith/people?utf8=%E2%9C%93&query=woodyrew

**Comment by fouad** [comment]
@woodyrew can you check now? it looks like the ui might've been broken because I just tried again, and I needed to click "change role" twice

**Comment by woodyrew** [comment]
All good now, thank you very much.
