### ISSUE TITLE
Blocking external styles in <head>

### ISSUE THREAD

**Issue by ismay** [metalsmith/metalsmith.io#280]
We're loading some external css (symbolset) for our icons. To speed things up we could concatenate it with our own styles, or use a different solution (like an svg library, which I personally would prefer).

**Comment by webketje** [comment]
A good resource about deferring non-critical CSS: https://web.dev/defer-non-critical-css/

**Comment by webketje** [comment]
Resolved in ba69888 and tested with Lighthouse (loading time decrease of 25%)
