### ISSUE TITLE
Unify sizing

### ISSUE THREAD

**Issue by ismay** [metalsmith/metalsmith.io#281]
In our css we have some sizing variables that we're not using everywhere for sizing. I want to see if that can be changed (without going overboard). It'd make maintaining a steady vertical rhythm easier.

(It'll also be a good opportunity to go through all the styles and see if there's anything else to address)

**Comment by webketje** [comment]
After analyzing the CSS I can't seem to find any such occurences.. Please re-open if you can still find any.
