### ISSUE TITLE
Split single page into multiple pages

### ISSUE THREAD

**Issue by ismay** [metalsmith/metalsmith.io#284]
We have enough content to warrant splitting it up into multiple pages, and adding some navigation. Currently it is not easy to navigate.

To guide us, it would be good if we think about the different purposes a visitor might have, so that hopefully most visitors will be able quickly find what they're looking for. The ones I can think of:

- What is metalsmith (just exploring).
- Comparing static site generators (what sets metalsmith apart from other ssg).
- Looking for a getting started guide (new user, wants to use metalsmith, doesn't know how to start).
- Looking for documentation (more advanced user, wants to know specific api info).
- Looking for plugins / a specific plugin.

**Comment by leviwheatcroft** [comment]
Good point, desperately need navigation. Splitting to separate pages should be carefully considered. 

I think your first two purposes "what is metalsmith" & "comparing static site generators" should both be on the front page. 
Plugin list should have it's own page.
As for documentation, I suppose the existing documentation on the front page should be contained in a single separate page, with internal / on page navigation.

**Comment by webketje** [comment]
Offering my input on this: It would be much easier to read and SEO-wise better to have separate pages like most modern build tools/ site generators have (looking at [Hexo](https://hexo.io/), [Next.js](https://nextjs.org), and [Gatsby](https://www.gatsbyjs.org)). Most of the generators mentioned above have:

- A homepage with a process visualization, feature spotlights and clickthrough call-to-actions to other pages
- Either a single docs page with tutorial/ Getting started/ Guide & API, or 2 separate pages.
- A plugin search page
- A features page (= comparison with competition)
