### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by webketje** [metalsmith/metalsmith.io#315]
- add 404.njk.md to the source dir
- title: We're still busy forging this page (or if you know something more clever, feel free)
- draft: true
- slug: Page not found (<- this is used as tab title)
- Add "Back to home" link
- see https://www.metalsmith.io/docs for inspiration text

**Comment by SeeStokes** [comment]
@webketje Can I take a stab at this? I'm learning tech writing and looking for open source projects to contribute to.
