### ISSUE TITLE
Categorizing the plugins would be nice

### ISSUE THREAD

**Issue by jocelynlecomte** [metalsmith/metalsmith.io#54]
The plugins section of the site is starting to be huge, and it's getting difficult to find / track plugins. It would be nice to categorize the plugins, and to have a 'new' section.

**Comment by mcdonnelldean** [comment]
I think a search at the top would be awesome, especially if it autofiltered the page. It would make searching for plugins really handy.

**Comment by woodyrew** [comment]
I just noticed this has been implemented. See: http://www.metalsmith.io/#the-plugins filter section.
